### PR TITLE
avoid parser exception on 204 no content

### LINKED ISSUE #95: Fix unwanted exception on Delete Flight Order Management API
The [Flight Orders Management API](https://developers.amadeus.com/self-service/category/air/api-doc/flight-order-management) returns en empty body with status code 204 when an order is deleted successfully. The SDK doesn't handle this use case properly; it throws a ParserException as the API does not return a FlightOrder object, instead returns the empty response with code 204.

How to reproduce
```
import com.amadeus.Amadeus;
import com.amadeus.booking.FlightOrder;
import com.amadeus.exceptions.ResponseException;

public class FlightOrderManagement {
    public static void main(String[] args)  throws ResponseException {
      Amadeus amadeus = Amadeus
              .builder("client_key","client_secret")
              .build();
      com.amadeus.resources.FlightOrder order = amadeus.booking.flightOrder("eJzTd9cP8A8y8nIDAAtUAlk").delete();

      if (order.getResponse().getStatusCode() != 204) {
        System.out.println("Wrong status code: " + order.getResponse().getStatusCode());
        System.exit(-1);
      }

      System.out.println("deleted");
     }
}
```

```
Exception in thread "main" com.amadeus.exceptions.ParserException: [204]
        at com.amadeus.Response.detectError(Response.java:79)
        at com.amadeus.HTTPClient.execute(HTTPClient.java:361)
        at com.amadeus.HTTPClient.unauthenticatedRequest(HTTPClient.java:253)
        at com.amadeus.HTTPClient.request(HTTPClient.java:339)
        at com.amadeus.HTTPClient.delete(HTTPClient.java:94)
        at com.amadeus.booking.FlightOrder.delete(FlightOrder.java:85)
        at com.amadeus.booking.FlightOrder.delete(FlightOrder.java:95)
        at flightsearch.FlightSearch.main(FlightSearch.java:17)
```

### PR DESCRIPTION
**Pull request by tsolakoua**
Fixes #95

### CODE REVIEW

File: src/main/java/com/amadeus/Response.java [hunk 1]
```diff
@@ -121,6 +121,11 @@ private void parseData(HTTPClient client) {
 
   // Tries to read the body.
   private String readBody() {
+    // Workaround to avoid ParserException when status code is 204
+    if (statusCode == 204) {
+      body = "{ \"data\": { } } ";
```
Comment (anthonyroux) [inline src/main/java/com/amadeus/Response.java:126]: Does it mean you want the SDK to return a body "{ \"data\": { } } " when doing a delete?

File: src/main/java/com/amadeus/Response.java [hunk 2]
```diff
@@ -67,6 +66,9 @@ protected void parse(HTTPClient client) {
   // Detects of any exceptions have occured and throws the appropriate exceptions.
   protected void detectError(HTTPClient client) throws ResponseException {
     ResponseException exception = null;
+    if (statusCode == 204) {
```
Comment (anthonyroux) [inline src/main/java/com/amadeus/Response.java:69]: should it be part of the if else if else if part instead of being an if isolated?

File: src/main/java/com/amadeus/Response.java [hunk 3]
```diff
@@ -97,6 +99,9 @@ private void parseStatusCode() {
 
   // Tries to parse the data
   private void parseData(HTTPClient client) {
+    if (this.statusCode == 204) {
```
Comment (anthonyroux) [inline src/main/java/com/amadeus/Response.java:102]: Instead of having it here with an empty return could it be in the same file line 64 (in the parse method) with something like: 
```java
 protected void parse(HTTPClient client) {
    parseStatusCode();
    if(this.statusCode != 204) {
         parseData(client);
   }
  }
```

**Review by anthonyroux — CHANGES_REQUESTED** [review]
Did it impact the unit-tests?

**Review by anthonyroux — APPROVED** [review]
